name: workflow

on:
  pull_request:
  push:
  branches:
       - master
       - develop

jobs:
   build:
   runs-on: ubuntu-latest
   
   strategy:
    matrix:
    node-version: [8.x, 10.x, 12.x]
    
   steps:
  - uses: action/checkout@v1
  - name: Use Node.js ${{matrix.node-version}}
    uses: action/setup-node@v1
    with:
     node-version: ${{matrix.node-version}}
  - name: npm install,build, and test
    run: 
      npm ci
      npm run build --if--present
      npm test
    env:
     CI: true
   
   
