
name: github action example

on: 
  pull_request:
  push:
    branches:
      - main
      - develop
jobs:
  test:
    name: Compile Build & Deploy
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Use Example.js ${{matrix.node-version}}
       uses: actions/setup-node@v1
       with:
          node-version: ${{matrix.node-version}}
     - name: Install
       run: npm install
     - name: Test
       run: npm test
